{
 "title": "Benchmark",
 "time": { "from": "2025-01-01T00:10:00.000Z", "to": "2025-01-01T00:21:00.000Z" },
 "panels": [
  {
   "title": "Q1: End to end Time vs Worker Count",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "keyName": " bench:grafana:line:e2e:Q1",
     "query": "HVALS bench:grafana:line:e2e:Q1",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Q1 - Processing time vs workers: DataFrame vs RDD",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "keyName": " bench:grafana:line:e2e:Q1",
     "query": "HVALS bench:grafana:line:processing:Q1",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Q2: End to end Time vs Worker Count",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "keyName": " bench:grafana:line:e2e:Q1",
     "query": "HVALS bench:grafana:line:e2e:Q2",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Q2 - Processing time vs workers: DataFrame vs RDD",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "keyName": " bench:grafana:line:e2e:Q1",
     "query": "HVALS bench:grafana:line:processing:Q2",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Q3: End to end Time vs Worker Count",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "keyName": " bench:grafana:line:e2e:Q1",
     "query": "HVALS bench:grafana:line:e2e:Q3",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Q3 - Processing time vs workers: DataFrame vs RDD",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "keyName": " bench:grafana:line:e2e:Q1",
     "query": "HVALS bench:grafana:line:processing:Q3",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Statistiche Aggregate",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "HVALS bench:grafana:table:aggregate",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "query": "HVALS bench:grafana:box:e2e:Q1", "type": "cli" }
   ]
  },
  {
   "title": "Q1 - End-to-end benchmark distribution",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 32 },
   "targets": [
    {
     "query": "HVALS bench:grafana:boxstats:e2e:Q1",
     "type": "cli"
    }
   ]
  }
 ]
}